name = "looterio-search"
main = "src/index.js"
compatibility_date = "2024-09-23"

[[kv_namespaces]]
binding = "LOOTERIO_IDX"
id = "2410dc0975554a3b89af1a9fd1e60359"
preview_id = "2410dc0975554a3b89af1a9fd1e60359"

# Set secret via: wrangler secret put LOOTERIO_SECRET
