name = "loot-market"
main = "src/index.js"
account_id = "fa13ade67afbe9a6aceaa06051f0572b"
compatibility_date = "2026-09-01"

[vars]
TREASURY_OWNER = "G1NaEsx5Pg7dSmyYy6Jfraa74b7nTbmN9A9NuiK171Ma"
TREASURY_USDC = "C3YvVCiAMwZ6Yz4ZAJWY7fcFo8upJD9xd9Mrpc9VkHuC"
USDC_MINT = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
IDEAS_TOTAL = "100"
PRICE_IDEA = "9"
PRICE_BEER = "1"
ALLOWED_ORIGIN = "https://looterstudio.xyz"

[[kv_namespaces]]
binding = "LOOT"
id = "1c3350b92cd04eefbd21d6bdf6ae6ea2"
